$(function(){"use strict";var s=$(window);$('a[href*="#"]:not([href="#"])').on("click",function(){if(location.pathname.replace(/^\//,"")==this.pathname.replace(/^\//,"")||location.hostname==this.hostname){var a=$(this.hash);if((a=a.length?a:$("[name="+this.hash.slice(1)+"]")).length)return $("html,body").animate({scrollTop:a.offset().top-75},1e3),!1}}),s.on("scroll",function(){var a=s.scrollTop(),t=$(".navbar");200<a?(t.addClass("nav-scroll"),$(".navbar-brand img").attr("src","img/blog/anfotal.png")):(t.removeClass("nav-scroll"),$(".navbar-brand img").attr("src","img/blog/anfotal.png"))}),$(".cover-bg").each(function(){var a=$(this).attr("data-image-src");void 0!==a&&!1!==a&&$(this).css("background-image","url("+a+")")}),s.on("scroll",function(){$(".bar span").each(function(){var a=$(this).offset().top+$(this).outerHeight(),t=$(window).scrollTop()+$(window).height(),s=$(this).attr("data-width");a<t&&$(this).css({width:s})})});var t=!0;s.on("scroll",function(){var a=s.scrollTop();$(".services").offset().top-700<=a&&t&&($(".svg-icon").each(function(){$(".svg-icon").drawsvg({duration:4e3}).drawsvg("animate")}),t=!1)}),$(".testimonial .carousel-slick").slick({slidesToShow:3,slidesToScroll:1,autoplay:!0,dots:!0,autoplaySpeed:2e3,responsive:[{breakpoint:991,settings:{arrows:!1,centerMode:!0,centerPadding:"5px",slidesToShow:1,dots:!0}}]}),$(".about .box-text .owl-carousel").owlCarousel({loop:!0,items:1,margin:30,dots:!1,nav:!0,navText:['<span> <i class="jam jam-arrow-left"></i> </span>','<span> <i class="jam jam-arrow-right"></i> </span>']}),$(".services .owl-carousel").owlCarousel({loop:!0,items:3,margin:30,dots:!1,nav:!0,navText:['<span> <i class="jam jam-arrow-left"></i> </span>','<span> <i class="jam jam-arrow-right"></i> </span>'],responsiveClass:!0,responsive:{0:{items:1},991:{items:3}}}),$("#contact-form").validator(),$("#contact-form").on("submit",function(a){if(!a.isDefaultPrevented()){return $.ajax({type:"POST",url:"contact.php",data:$(this).serialize(),success:function(a){var t="alert-"+a.type,s=a.message,o='<div class="alert '+t+' alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>'+s+"</div>";t&&s&&($("#contact-form").find(".messages").html(o),$("#contact-form")[0].reset())}}),!1}})}),$(window).on("load",function(){$("#preloader").fadeOut(500);var t=$(".gallery").isotope({});$(".gallery").isotope({itemSelector:".item-img",transitionDuration:"0.5s"}),$(".gallery .single-image").fancybox({transitionIn:"elastic",transitionOut:"elastic",speedIn:600,speedOut:200,overlayShow:!1}),$(".filtering").on("click","button",function(){var a=$(this).attr("data-filter");t.isotope({filter:a})}),$(".filtering").on("click","button",function(){$(this).addClass("active").siblings().removeClass("active")})});

    function downloadJSAtOnload() {
        var element = document.createElement("script");
        element.src = "example.js";
        document.body.appendChild(element);
    }
    if (window.addEventListener)
        window.addEventListener("load", downloadJSAtOnload, false);
    else if (window.attachEvent)
        window.attachEvent("onload", downloadJSAtOnload);
    else window.onload = downloadJSAtOnload;
